- type: job
  id: Blueshield
  name: офицер "Синий Щит"
  description: Cпециально обученный сотрудник NanoTrasen, высланный на станцию Центральным Командованием для защиты Капитана, Командного состава и VIP-персон с ЦК.
  playTimeTracker: JobBlueshield
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000
  startingGear: BlueshieldGear
  icon: "JobIconBlueshield"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Command
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Cargo
  - Atmospherics
  - Cargo
  - Medical
  - Blueshield
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueshieldGear
  equipment:
    head: ClothingHeadHatBeretNavyBlue
    neck: ClothingNeckCloakShcloack
    back: ClothingBackpackSatchel
    belt: ClothingBeltSecurity
    shoes: ClothingShoesBootsCombat
    jumpsuit: ClothingUniformJumpsuitBlueshield
    eyes: ClothingEyesGlassesBlueshield
    outerClothing: ClothingOuterArmorBulletproof
    id: BlueshieldPDA
    ears: ClothingHeadsetAltCommand
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - Flash
